name: Auto Label Issues

on:
  issues:
    types: [opened, edited]

jobs:
  label_issues:
    runs-on: ubuntu-latest
    
    permissions:
      issues: write
      
    steps:
      - name: Add labels based on title
        uses: actions/github-script@v7
        with:
          script: |
            const title = context.payload.issue.title.toUpperCase();
            const labelsToAdd = [];

            if(title.includes('[FEAT]')){
              labelsToAdd.push('feat');
            }

            if(title.includes('[FIX]')){
              labelsToAdd.push('fix');
            }

            if(title.includes('[DOCS]')){
              labelsToAdd.push('docs');
            }

            if(title.includes('[STYLE]')){
              labelsToAdd.push('style');
            }

            if(title.includes('[REFACTOR]')){
              labelsToAdd.push('refactor');
            }

            if(title.includes('[TEST]')){
              labelsToAdd.push('test');
            }

            if(title.includes('[BUILD]')){
              labelsToAdd.push('build');
            }

            if(title.includes('[CI]')){
              labelsToAdd.push('ci');
            }

            if(title.includes('[CHORE]')){
              labelsToAdd.push('chore');
            }

            if(labelsToAdd.length > 0){
              await github.rest.issues.addLabels({
                owner: context.repo.owner,
                repo: context.repo.repo,
                issue_number: context.payload.issue.number,
                labels: labelsToAdd
              });
            }
